### ISSUE TITLE
Add ability to define object and array structures

### ISSUE THREAD

**Issue by displague** [jefftriplett/frontmatter-cli#5]
It would be useful to be able to work with more elaborate, bespoke, frontmatter formats.

For example:
```sh
$ echo "hello" | frontmatter-cli --versions[0].version="1.2.3" - -
---
versions:
- version: 1.2.3
---

hello
```

The current behavior results in:
```sh
$ echo "hello" | frontmatter-cli --versions[0].version="1.2.3" - -
---
versions[0].version: 1.2.3
---

hello
```

**Comment by jefftriplett** [comment]
Thank you for opening an issue. Since this is a thin wrapper around https://github.com/eyeseast/python-frontmatter it might be worth while opening an issue there on the off chance they want to support it. 

I'm open to using another frontmatter library, especially if there is one that handle toml+json frontmatter better, but I haven't looked for one yet.

**Comment by displague** [comment]
In that case, since the library can manage complex structures, I think this would be less about the frontmatter support and more about the command line parsing. 

ChatGPT suggests `dpath`: https://chat.openai.com/share/6700fbde-7f9e-41dc-ba0e-c034cd5f4259

**Comment by jefftriplett** [comment]
Ahh, I was missing that the cli was falling down on the option parsing. Interesting. I think this is also the first time someone has ChatGPT'ed a solution to me on a project.

I'm a bit tight on time for a few weeks, but if you want to PR something and test it, I can free up some time to review, merge, and release an update.

**Comment by displague** [comment]
>  I think this is also the first time someone has ChatGPT'ed a solution to me on a project.

It's the first time I've done it too (offered "here's what chatgpt says" on GitHub).  It seems more authenticate then just giving you the suggestion as though it was my own and it was more efficient than googling for python packages that do argument parsing and support a sort of json path syntax. 

We'll look back at this someday and say, "Wasn't that swell.. When you could post an issue and someone would respond, and someone would suggest an approach, and someone would try it out, and this whole conversation would emerge about a few lines of code. You never hear about developers anymore. They must still exist, right?"
