### ISSUE TITLE
Broken? No output with extra config

### ISSUE THREAD

**Issue by lmmx** [jefftriplett/frontmatter-cli#7]
I tried the demo and it doesn't seem to be working any more

```
echo "Hello"| frontmatter --title="Hello world"
```

gives no output

If I just pass a file and pipe to `frontmatter-cli` I get

```md
---
{}
---
```

Great idea though, I really want something like this to get and set key/value pairs in YAML frontmatter without scripting

**Comment by jefftriplett** [comment]
@lmmx Trying passing two `- -` See below:

```shell
➜ echo "Hello"| frontmatter --title="Hello world" - -
---
title: Hello world
---

Hello

```

That said, I'll give `click` another look and see if they have resolved this. I couldn't find a workaround when I last checked, but that was 6 to 9 months ago. See the defaults: https://github.com/jefftriplett/frontmatter-cli/blob/main/frontmatter_cli/cli.py#L32-L33

**Comment by lmmx** [comment]
Oh I'm sorry if it was user error no need to! As you were :-D

**Comment by jefftriplett** [comment]
All good. It prompted me to look again. I would prefer for the defaults to actually be a default 😆
